### ISSUE TITLE
Show created at in locations list on map page

### ISSUE THREAD

**Issue by sanketmaru** [sanketmaru/device-tracker#20]
Show created at in locations list on map page

**Comment by sanketmaru** [comment]
Also show when the user was at location , location object has the created at field.

**Comment by anandgupta193** [comment]
@sanketmaru --> Attaching the screenshot.

![image](https://user-images.githubusercontent.com/24511864/29938363-25039bb4-8ea6-11e7-9669-05cbc676ccea.png)

Please let me know if this is fine or we need to convert the ISO Date string to another format.
